

title: En Ugle
subtitle: Hej
description: >- # this means to ignore newlines until "baseurl:"
  En lille ugle l√¶rte fransk
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
plugins:
  - jekyll-feed


# remote_theme: "mmistakes/so-simple-theme@3.2.0"
# skin: "/assets/css/skins/default.css"
# #title: "Une Petite Chouette 2020"
# description: "SocialData2020"
#
#
# body {
#       font-family: "Times New Roman", Times, serif;
# }
#
#
# liquid:
#   error_mode: strict
#
# # Build settings
# permalink: /:categories/:title/
# markdown: kramdown
# feed:
#   path: atom.xml
#
#
# # Search
# search_full_content: false # can have performance implications for large sites
#
#
#
# plugins:
#   - jekyll-seo-tag
#   - jekyll-sitemap
#   - jekyll-feed
#   - jekyll-paginate
#
# # Front Matter Defaults
# defaults:
#   # Posts defaults
#   - scope:
#       path: "_posts"
#       type: posts
#     values:
#       layout: post
#       share: true
